####################################
from re import M


WIDTH = 800
HEIGHT = 800
FPS =  50

MENU_WIDHT = 400
MENU_HEIGHT = 400



##SNAKE
SNAKE_START_X = int(WIDTH/2)
SNAKE_START_Y = int(HEIGHT/2)
SNAKE_BLOCK_SIZE = 25
SNAKE_EYE_SIZE = 4


# WINDOW
WALL_TOPLEFT_X = 0
WALL_TOPLEFT_Y = 0
WALL_THICKNESS = 2 * SNAKE_BLOCK_SIZE
WALL_WIDHT = WIDTH
WALL_HEIGHT = HEIGHT

# SCORES
SCORE_X = WALL_TOPLEFT_X + WALL_THICKNESS
SCORE_Y = WALL_TOPLEFT_Y + 10
HIGH_SCORE_X = WIDTH - 200
HIGH_SCORE_Y = SCORE_Y 
FONT_URL = "res/fonts/Marcellus-Regular.ttf"
FONT_SIZE = 25

# FOOD 
FOOD_IMG_WIDTH = 20
FOOD_IMG_HEIGHT = FOOD_IMG_WIDTH
FOOD_URL = "res/imgs/food.png"


# COLORS
WALL_COLOR = (0,110, 0)
FONT_COLOR = (255, 255, 0)
SNAKE_HEAD = (60,60,0) ##NOTE: change me if you don't like my head, plz
SNAKE_BODY = (255, 255,0)
INIT_SNAKE_DIRECTION = 2 # 1 is up, 2 is right, 3 is down, 4 is left


####################################
